"""Data source adapter for macro economic indicators.

This module provides an adapter that loads macro indicator entities and
correlations from JSON files generated by the macro_indicators module.
"""

import json
from pathlib import Path
from typing import Any
from src.data.adapter import DataSourceAdapter


class MacroIndicatorsAdapter(DataSourceAdapter):
    """Adapter for macro economic indicator data.

    Loads macro indicators and their correlations from JSON files:
    - data/macro_indicators.json: Entity definitions
    - data/macro_correlations.json: Correlation relationships

    Example:
        adapter = MacroIndicatorsAdapter()

        # Load entities
        entities_raw = adapter.load_entities()
        print(f"Loaded {len(entities_raw)} macro indicators")

        # Load relationships
        rels_raw = adapter.load_relationships()
        print(f"Loaded {len(rels_raw)} correlations")
    """

    def __init__(self, data_dir: str = "data"):
        """Initialize adapter.

        Args:
            data_dir: Directory containing JSON files (default: "data")
        """
        self.data_dir = Path(data_dir)
        self.entities_file = self.data_dir / "macro_indicators.json"
        self.relationships_file = self.data_dir / "macro_correlations.json"

    def load_entities(self) -> list[dict[str, Any]]:
        """Load macro indicator entities from JSON.

        Returns:
            List of entity dicts with keys:
                - id: Indicator ID (e.g., "FED_FUNDS_RATE")
                - name: Human-readable name
                - type: "indicator"
                - attributes: Dict with source, latest_value, etc.

        Returns empty list if file doesn't exist.
        """
        if not self.entities_file.exists():
            print(f"[MacroAdapter] No entities file found at {self.entities_file}")
            return []

        with open(self.entities_file) as f:
            entities = json.load(f)

        print(f"[MacroAdapter] Loaded {len(entities)} macro indicator entities")
        return entities

    def load_relationships(self) -> list[dict[str, Any]]:
        """Load macro correlation relationships from JSON.

        Returns:
            List of relationship dicts with keys:
                - source: Macro indicator ID
                - target: Stock ticker
                - correlation: Correlation value (-1 to 1)
                - p_value: Statistical significance
                - relationship_type: "correlated" or "inverse_correlated"

        Returns empty list if file doesn't exist.
        """
        if not self.relationships_file.exists():
            print(f"[MacroAdapter] No relationships file found at {self.relationships_file}")
            return []

        with open(self.relationships_file) as f:
            relationships = json.load(f)

        print(f"[MacroAdapter] Loaded {len(relationships)} macro correlation relationships")
        return relationships

    def normalize_relationships(self, raw: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Convert macro correlations to standardized CausalLink format.

        Args:
            raw: Raw correlation data from load_relationships()

        Returns:
            Normalized relationship dicts ready for CausalLink creation

        Each relationship is converted to have:
        - source, target, relationship_type (from raw data)
        - strength: abs(correlation) mapped to 0-1
        - delay_mean: 0.0 (correlations are instantaneous)
        - delay_std: 1.0 (low variance)
        - confidence: 1.0 - p_value (lower p = higher confidence)
        - direction: +1 or -1 based on correlation sign
        - attributes: Contains original correlation and p_value
        """
        normalized = []

        for rel in raw:
            correlation = rel["correlation"]
            p_value = rel["p_value"]

            # Map correlation to strength (absolute value, 0-1)
            strength = abs(correlation)

            # Correlation is instantaneous (no time delay)
            delay_mean = 0.0
            delay_std = 1.0  # Low variance for instantaneous correlations

            # Direction: +1 for positive, -1 for negative
            direction = 1.0 if correlation > 0 else -1.0

            # Confidence: inverse of p-value (clamped to 0-1)
            confidence = max(0.0, min(1.0, 1.0 - p_value))

            normalized.append({
                "source": rel["source"],
                "target": rel["target"],
                "relationship_type": rel["relationship_type"],
                "strength": strength,
                "delay_mean": delay_mean,
                "delay_std": delay_std,
                "confidence": confidence,
                "direction": direction,
                "attributes": {
                    "correlation": correlation,
                    "p_value": p_value,
                    "data_source": "macro_correlation",
                },
            })

        return normalized
