"""Graph builder for macro economic indicators.

This module builds a causal graph from macro economic indicator data,
including entities (Fed rate, CPI, oil, gold, VIX, etc.) and their
correlation-based relationships with securities.
"""

from src.core.graph import CausalGraph, Entity, CausalLink
from src.adapters.macro import MacroIndicatorsAdapter


def build_macro_graph(**kwargs) -> CausalGraph:
    """Build graph from macro economic indicators.

    Loads macro indicator entities and their correlations with securities
    from JSON files generated by the macro_indicators data fetcher.

    Args:
        **kwargs: Optional keyword arguments:
            - data_dir (str): Directory containing JSON files (default: "data")
            - min_confidence (float): Minimum confidence threshold (0-1)

    Returns:
        CausalGraph with macro indicator entities and correlation relationships

    Example:
        # Build macro graph
        graph = build_macro_graph()
        print(f"Macro graph: {len(graph.entities)} entities, "
              f"{len(list(graph.iter_links()))} links")

        # Access entities
        fed_rate = graph.get_entity("FED_FUNDS_RATE")
        print(f"Fed Funds Rate: {fed_rate.name}")

        # Get correlations
        links = [link for link in graph.iter_links() if link.source == "FED_FUNDS_RATE"]
        print(f"Fed rate correlates with {len(links)} entities")
    """
    graph = CausalGraph()

    # Get optional parameters
    data_dir = kwargs.get("data_dir", "data")
    min_confidence = kwargs.get("min_confidence", 0.0)

    # Initialize adapter
    adapter = MacroIndicatorsAdapter(data_dir=data_dir)

    # Load entities
    entities_raw = adapter.load_entities()

    if not entities_raw:
        print("[MacroBuilder] ⚠️  No macro indicator entities found. "
              "Run scripts/generate_macro_data.py first.")
        return graph

    entities_normalized = adapter.normalize_entities(entities_raw)

    for entity_data in entities_normalized:
        entity = Entity(
            id=entity_data["id"],
            entity_type=entity_data["type"],
            name=entity_data["name"],
            attributes=entity_data.get("attributes", {}),
        )
        graph.add_entity(entity)

    print(f"[MacroBuilder] Added {len(entities_normalized)} macro indicator entities")

    # Load relationships
    relationships_raw = adapter.load_relationships()

    if not relationships_raw:
        print("[MacroBuilder] ⚠️  No macro correlations found. "
              "Run scripts/generate_macro_data.py first.")
        return graph

    relationships_normalized = adapter.normalize_relationships(relationships_raw)

    # Filter by confidence if specified
    if min_confidence > 0:
        before_count = len(relationships_normalized)
        relationships_normalized = [
            rel for rel in relationships_normalized
            if rel["confidence"] >= min_confidence
        ]
        filtered_count = before_count - len(relationships_normalized)
        if filtered_count > 0:
            print(f"[MacroBuilder] Filtered out {filtered_count} "
                  f"low-confidence relationships (< {min_confidence})")

    # Create CausalLink objects and store them
    # Links to stock entities will be added during graph merge
    pending_links = []
    skipped_links = 0

    for rel_data in relationships_normalized:
        # Check if source (indicator) exists
        if rel_data["source"] not in graph.entities:
            skipped_links += 1
            continue

        # Get attributes for evidence
        attrs = rel_data.get("attributes", {})
        correlation = attrs.get("correlation", 0.0)
        p_value = attrs.get("p_value", 1.0)

        link = CausalLink(
            source=rel_data["source"],
            target=rel_data["target"],
            relationship_type=rel_data["relationship_type"],
            strength=rel_data["strength"],
            delay_mean=rel_data["delay_mean"],
            delay_std=rel_data["delay_std"],
            confidence=rel_data["confidence"],
            direction=rel_data["direction"],
            evidence=[f"Correlation: {correlation:.3f} (p={p_value:.4f})"],
            source_type="macro_correlation",
        )

        pending_links.append(link)

    # Store pending links in graph for later addition after merge
    # We use a custom attribute to avoid validation errors
    graph._pending_macro_links = pending_links

    print(f"[MacroBuilder] Prepared {len(pending_links)} macro correlation links (will be added after merge)")

    if skipped_links > 0:
        print(f"[MacroBuilder] Skipped {skipped_links} relationships "
              f"(source indicator not found)")

    return graph


# Register this builder with the global registry
# This happens when the module is imported
try:
    from src.graph.builders.registry import BuilderRegistry

    BuilderRegistry.register("macro", build_macro_graph)
    print("[MacroBuilder] ✓ Registered 'macro' domain builder")
except ImportError:
    # Registry not available yet (module initialization order)
    pass
